version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: fastapi_app
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db/orders
    depends_on:
      - db
    ports:
      - "8000:8000"